# Site settings
title: Malav Bhavsar
description: 'Hello, my name is Malav Bhavsar. I am a Full Stack Engineer at Rocket Fuel. I lead UI development for our Brand product.'
url: 'http://malav.io'
baseurl: '/'
google_analytics: 'UA-72841310-1'

author:
  name: 'Malav Bhavsar'
  email: 'malav.bhavsar@gmail.com'
  twitter_username: malavbhavsar
  github_username:  malavbhavsar
  linkedin_username:  malavbhavsar

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-paginate
  - jekyll-redirect-from

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
